/*\r\nMySQL Database Backup Tools\r\nServer:localhost:3306\r\nDatabase:test\r\nData:2020-11-23 08:58:56\r\n*/\r\nSET FOREIGN_KEY_CHECKS=0;\r\n-- ----------------------------\r\n-- Table structure for tsj_articles\r\n-- ----------------------------\r\nDROP TABLE IF EXISTS `tsj_articles`;\r\nCREATE TABLE `tsj_articles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `order_by` smallint(6) unsigned DEFAULT '0' COMMENT '排序',
  `type` smallint(6) unsigned DEFAULT '0' COMMENT '分类id',
  `title` varchar(255) NOT NULL COMMENT '标题',
  `subtitle` varchar(255) DEFAULT NULL COMMENT '副标题',
  `publisher` varchar(255) DEFAULT NULL COMMENT '作者',
  `summary` text COMMENT '简介',
  `content` text COMMENT '内容',
  `cover` varchar(255) DEFAULT NULL COMMENT '封面',
  `covers` varchar(255) DEFAULT NULL COMMENT '多图',
  `qr_code` varchar(255) DEFAULT NULL COMMENT '二维码',
  `bg_color` varchar(255) DEFAULT NULL COMMENT '背景色',
  `bg_pic` varchar(255) DEFAULT NULL COMMENT '背景图',
  `url` varchar(255) DEFAULT NULL COMMENT '链接',
  `tags` varchar(255) DEFAULT NULL COMMENT '标签',
  `views` int(10) unsigned DEFAULT '0' COMMENT '查看数',
  `index_show` tinyint(1) DEFAULT '0' COMMENT '首页显示',
  `created_at` int(11) unsigned DEFAULT '0',
  `updated_at` int(11) DEFAULT NULL,
  `status` tinyint(1) DEFAULT '1' COMMENT '状态：1 启用 0停用',
  `name` varchar(255) DEFAULT NULL COMMENT '所属栏目',
  `keywords` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=15 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='新闻表';\r\n-- ----------------------------\r\n-- Records of tsj_articles\r\n-- ----------------------------\r\nINSERT INTO `tsj_articles` (`id`,`order_by`,`type`,`title`,`subtitle`,`publisher`,`summary`,`content`,`cover`,`covers`,`qr_code`,`bg_color`,`bg_pic`,`url`,`tags`,`views`,`index_show`,`created_at`,`updated_at`,`status`,`name`,`keywords`) VALUES ('13','10','25','api测试修改4','','','','','','','','','','','','0','0','1588061545','1592553067','1','','');\r\nINSERT INTO `tsj_articles` (`id`,`order_by`,`type`,`title`,`subtitle`,`publisher`,`summary`,`content`,`cover`,`covers`,`qr_code`,`bg_color`,`bg_pic`,`url`,`tags`,`views`,`index_show`,`created_at`,`updated_at`,`status`,`name`,`keywords`) VALUES ('14','0','0','api测试','','','','','','','','','','','','0','0','1592466298','1592466298','1','','');\r\n\r\n-- ----------------------------\r\n-- Table structure for tsj_type\r\n-- ----------------------------\r\nDROP TABLE IF EXISTS `tsj_type`;\r\nCREATE TABLE `tsj_type` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `up_id` int(10) unsigned DEFAULT '0',
  `level` smallint(1) DEFAULT '1',
  `order_by` int(10) DEFAULT '0',
  `name` varchar(20) DEFAULT NULL,
  `title` varchar(50) NOT NULL,
  `subtitle` varchar(50) DEFAULT NULL,
  `cover` varchar(255) DEFAULT NULL,
  `summary` varchar(255) DEFAULT NULL,
  `bg_pic` varchar(255) DEFAULT NULL,
  `bg_color` varchar(10) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `status` tinyint(1) unsigned DEFAULT '1',
  `updated_at` int(10) unsigned DEFAULT NULL,
  `created_at` int(10) unsigned DEFAULT NULL,
  `covers` varchar(255) DEFAULT NULL,
  `seoTitle` varchar(255) DEFAULT NULL,
  `seoDescription` varchar(255) DEFAULT NULL,
  `seoKeywords` varchar(255) DEFAULT NULL,
  `english_name` varchar(255) DEFAULT NULL COMMENT '拼音简写',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=28 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='分类表';\r\n-- ----------------------------\r\n-- Records of tsj_type\r\n-- ----------------------------\r\n\r\n-- ----------------------------\r\n-- Table structure for tsj_user\r\n-- ----------------------------\r\nDROP TABLE IF EXISTS `tsj_user`;\r\nCREATE TABLE `tsj_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `auth_key` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password_hash` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password_reset_token` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `access_token` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `invalid_at` int(11) DEFAULT NULL,
  `mobile` varchar(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `group` tinyint(1) DEFAULT NULL,
  `avatar` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` tinyint(1) DEFAULT NULL,
  `created_ip` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_login_at` int(11) DEFAULT NULL,
  `login_times` int(11) DEFAULT NULL,
  `created_at` int(11) DEFAULT NULL,
  `updated_at` int(11) DEFAULT NULL,
  `last_login_ip` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `allowance` int(11) DEFAULT NULL,
  `allowance_updated_at` int(11) DEFAULT NULL,
  `qq` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\r\n-- ----------------------------\r\n-- Records of tsj_user\r\n-- ----------------------------\r\nINSERT INTO `tsj_user` (`id`,`username`,`auth_key`,`password_hash`,`password_reset_token`,`access_token`,`invalid_at`,`mobile`,`email`,`group`,`avatar`,`status`,`created_ip`,`last_login_at`,`login_times`,`created_at`,`updated_at`,`last_login_ip`,`allowance`,`allowance_updated_at`,`qq`) VALUES ('1','admin','7FyBcW4u0KcCgp1NQ57F1OrgArgNDhtn','$2y$13$l85pu7pFMGnkTpp8oeYjZOPN8NzH.1DJMOtpSowDKAFfGUuc9ASM2','','h7DaDNW0nKOaeYNnaJ1rSUZKYiXPcbRi_1603078499','1595659068','','','9','http://yii.vue.test/data/upload/20101913135056283.jpg','1','','1603261294','314','1597641216','1603263217','127.0.0.1','99999','1592560959','');\r\n\r\n